### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by 4censord** [turt2live/matrix-sticker-manager#21]
## To Reproduce

1. Set your matrix homeserver up to only use TLS1.3
2. Restart the stickermanager

```
MatrixLiteClient (REQ-1) GET https://matrix.domain.com/_matrix/client/r0/account/whoami
MatrixLiteClient (REQ-1) { Error: write EPROTO 140275250072904:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
(node:1) UnhandledPromiseRejectionWarning: Error: write EPROTO 140275250072904:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
stickermanager exited with code 0
```
it explicitly says `SSL alert number 70` which translates to `the protocoll the client tried to use is recognized, but not supported`

**Comment by 4censord** [comment]
So this seems to be related to the `FROM node:10-alpine` statement.
If this is changed to a later version (tested with `FROM node:15-alpine`) 
it works.
